// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ancafmaqvfkvrmdedfjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuY2FmbWFxdmZrdnJtZGVkZmpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NTMxMTQsImV4cCI6MjA2NTQyOTExNH0.W1OlR7JsuL8Vev23LB3AUCx7y2EUE2WeDd9TB75u4Fs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);